### ISSUE TITLE
Buttons Disappear When Resizing the Chrome Window

### ISSUE THREAD

**Issue by KingDave3** [Tetrax-10/imdb-tmdb-linker#2]
I've noticed that the TMDb and Letterboxd buttons are displayed correctly when the Chrome window is in full-screen mode. However, when I resize the window or split it (e.g., aligning it to the left or right of the screen), the TMDb and Letterboxd buttons completely disappear. This is only a problem in imdb sites

Steps to Reproduce:

Open the application in Chrome.
Ensure the window is in full-screen mode – all buttons are displayed correctly.
Resize the window or split it to one side of the screen (e.g., left or right).
Observe that the TMDb and Letterboxd buttons disappear.
Expected Behavior: The buttons should remain visible regardless of the window size, or there should be an alternative way to access them (e.g. becoming smaller, a responsive layout)

**Comment by Tetrax-10** [comment]
Ah, never thought of this test case. Thx for reporting, its a minor bug.

This script works on both mobile (small display) and desktop (big display). But I never thought of someone will resize the window or use small window on a desktop.

Fixed it!

**Comment by KingDave3** [comment]
Thanks! Works perfect now. Yeah for workflow reasons I often have 2 or even 3 windows open on one screen.
