### ISSUE TITLE
Implement IMDb link for Letterboxd person page

### ISSUE THREAD

**Issue by KingDave3** [Tetrax-10/imdb-tmdb-linker#3]
As I see this script works for 
LB link on TMDB
TMDB link on IMDB
nothing on LB (TMDB button is built by them already)

Would be cool to have the missing ones:
IMDB Link on TMDB
LB link on IMDB
IMDB link on LB

**Comment by Tetrax-10** [comment]
Did you paste your TMDB API key?

[Installation steps](https://github.com/Tetrax-10/imdb-tmdb-letterboxd-linker#installation)

**Comment by KingDave3** [comment]
Yes. Also, the imdb button on tmdb movie and tv entries does not appear - this worked on Movie Linker 0.2 which I now have turned off. tmdb button on imdb sometimes appears sometimes not.. thats a different issue though - should we discuss all of that in this post? First time posting on github.

Here are the three scenarios(movie, tv and peoples page) for imdb and tmdb:

![tmdbp](https://github.com/user-attachments/assets/8e23cd27-ebb1-451b-a035-b7fca6ad1dca)
![tmdbtv](https://github.com/user-attachments/assets/5ac360e3-98c4-4ba6-ade4-02589020a529)
![tmdbm](https://github.com/user-attachments/assets/df73549a-dbe6-4f0b-9d42-bb17d0a1c21d)


![imdbp](https://github.com/user-attachments/assets/1da2768e-6c59-479d-8206-30ab252c6332)
![imdbtv](https://github.com/user-attachments/assets/56827419-a4d7-45cb-80fc-88eb8642811a)
(^loading symbol is moving but is not changing)
![imdbm](https://github.com/user-attachments/assets/8bb6bd89-70af-4aa2-a770-d35b64e904e4)

**Comment by Tetrax-10** [comment]
- Make sure you are on latest version (2.2)
- Make sure you pasted your API key (32 characters) and not your token (longer than 100 characters)

If this issue still persists then post me a screenshot of your console tab in developer tools.

In version 2.2 I have improved the code with error handling and fixed some minor stuffs that may cause bugs in rare cases.

<br>

> tmdb button on imdb sometimes appears sometimes not.. thats a different issue though

I think this issue is related to this forum, so we can discuss it here. First we will fix the main issue that will prob solve this one too.

**Comment by KingDave3** [comment]
Well I somehow managed to save my api key wrong, the last number was missing.... sorry. The loading symbol now only appears in cases the entry does not exist on the other page. So everything works!

Do you plan to display IMDB link on LB for peoples pages too?

**Comment by Tetrax-10** [comment]
For the whole time I was assuming Letterboxd displayed IMDb link for person page.

![image](https://github.com/user-attachments/assets/25e360d1-1ced-4d62-8db1-fc1da6cc1666)

But it was actually showed by a [extension](https://github.com/duncanlang/Letterboxd-Extras/) I was using the whole time lol.

Yeah, sure I will implement it when I have time.

**Comment by Tetrax-10** [comment]
Done 👍
